//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Localidad = new HashSet<Localidad>();
        }
    
        // Primitive properties
    
        public int ID { get; set; }
        public int idProvincia { get; set; }
        public string Nombre { get; set; }
    
        // Navigation properties
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Localidad> Localidad { get; set; }
    
    }
}
