//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Proteinograma_Electroforetico
    {
        public tb_Analisis_Proteinograma_Electroforetico()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_proteinograma_electrof { get; set; }
        public Nullable<decimal> albumina { get; set; }
        public Nullable<decimal> globulina { get; set; }
        public Nullable<decimal> coheficiente_albumina_globulina { get; set; }
        public Nullable<decimal> alfaglobulina { get; set; }
        public Nullable<decimal> alfa1globulina { get; set; }
        public Nullable<decimal> alfa2globulina { get; set; }
        public Nullable<decimal> betaglobulina { get; set; }
        public Nullable<decimal> gammaglobullina { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
