//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Examen_MateriaFecal
    {
        public tb_Analisis_Examen_MateriaFecal()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_examen_mat_fecal { get; set; }
        public string examen_microsc_directo { get; set; }
        public string coloracion { get; set; }
        public string parasitos { get; set; }
        public string hongos { get; set; }
        public string fibras { get; set; }
        public string grasas { get; set; }
        public string almidon { get; set; }
        public string celulosa { get; set; }
        public string leucositos { get; set; }
        public string hematies { get; set; }
        public string celulas_epitaliales { get; set; }
        public string cristales_oxidos_calcio { get; set; }
        public string cristales_fosfatos { get; set; }
        public string cristales_charcot_layden { get; set; }
        public string reconocimiento_de_mucina { get; set; }
        public string reconocimiento_albuminas_complejas { get; set; }
        public string reconocimiento_albuminas_integradas { get; set; }
        public string reconocimiento_peptona { get; set; }
        public string reconocimiento_sangre_oculta { get; set; }
        public string ph { get; set; }
        public string coprocultivo { get; set; }
        public string gram { get; set; }
        public string antibiograma { get; set; }
        public string cultivo { get; set; }
        public string macroscopico_directo { get; set; }
        public string microscopico { get; set; }
        public string seriado_tecnica_vanni { get; set; }
        public string seriado_tecnica_deschiens { get; set; }
        public string seriado_carles_barthelemy { get; set; }
        public string seriado_willis { get; set; }
        public string seriado_faust { get; set; }
        public string recuento_huevos { get; set; }
        public string larvas { get; set; }
        public string test_graham { get; set; }
        public string huevos { get; set; }
        public string trofosoitos { get; set; }
        public string quistes { get; set; }
        public string levaduras { get; set; }
        public string otros { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
