//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Quimica_Hematica
    {
        public tb_Analisis_Quimica_Hematica()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_quimica_hematica { get; set; }
        public Nullable<decimal> glucemia { get; set; }
        public Nullable<decimal> uremia { get; set; }
        public Nullable<decimal> uricemia { get; set; }
        public Nullable<decimal> creatininemia { get; set; }
        public Nullable<decimal> trigliceridos { get; set; }
        public Nullable<decimal> colesterol { get; set; }
        public Nullable<decimal> hdl_colesterol { get; set; }
        public Nullable<decimal> ind_aterocidad_cociente_ldhcol_hdl_col { get; set; }
        public Nullable<decimal> ind_aterocidad_cociente_col_total_hdl { get; set; }
        public Nullable<decimal> lipido_total { get; set; }
        public Nullable<decimal> fosfatemia { get; set; }
        public Nullable<decimal> magnesemia { get; set; }
        public Nullable<decimal> calcemia { get; set; }
        public Nullable<decimal> cloremia { get; set; }
        public Nullable<decimal> ferremia { get; set; }
        public Nullable<decimal> hemoglobina_glicosilada { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
