//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Hormonas
    {
        public tb_Analisis_Hormonas()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_hormonas { get; set; }
        public byte[] hs_pcr { get; set; }
        public Nullable<decimal> cortisol_am { get; set; }
        public Nullable<decimal> cortisol_pm { get; set; }
        public Nullable<decimal> lh { get; set; }
        public Nullable<decimal> testosterona_libre { get; set; }
        public Nullable<decimal> testosterona_total { get; set; }
        public Nullable<decimal> fsh { get; set; }
        public Nullable<decimal> estriadol { get; set; }
        public Nullable<decimal> shbg { get; set; }
        public Nullable<decimal> psa { get; set; }
        public Nullable<decimal> cea { get; set; }
        public string helicobacter_pilori { get; set; }
        public Nullable<decimal> prolactina { get; set; }
        public Nullable<decimal> testosterona { get; set; }
        public Nullable<decimal> t3 { get; set; }
        public Nullable<decimal> t4_total { get; set; }
        public Nullable<decimal> tsh { get; set; }
        public Nullable<decimal> test_tolerancia_glucosa_v1 { get; set; }
        public Nullable<decimal> test_tolerancia_glucosa_v2 { get; set; }
        public Nullable<decimal> test_tolerancia_glucosa_v3 { get; set; }
        public Nullable<decimal> test_tolerancia_glucosa_v4 { get; set; }
        public string cetoesteroides_neutros_urinarios { get; set; }
        public Nullable<decimal> alfa_fetoproteina { get; set; }
        public Nullable<decimal> estrogenos_totales { get; set; }
        public Nullable<decimal> estriol { get; set; }
        public Nullable<decimal> estrona { get; set; }
        public Nullable<decimal> pregnandriol { get; set; }
        public Nullable<decimal> pregnantriol { get; set; }
        public Nullable<decimal> progesterona { get; set; }
        public Nullable<int> analisis_id { get; set; }
        public Nullable<int> estado_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
