//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Hemograma
    {
        public tb_Analisis_Hemograma()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_hemograma { get; set; }
        public Nullable<decimal> globulos_rojos { get; set; }
        public Nullable<decimal> globulos_blancos { get; set; }
        public Nullable<decimal> hematocrito { get; set; }
        public Nullable<decimal> conc_hemoglobina_corpuscular_media { get; set; }
        public Nullable<decimal> volumen_corpuscular_medio { get; set; }
        public Nullable<decimal> hemoglobina_corpuscular_media { get; set; }
        public Nullable<decimal> celulas_juveniles { get; set; }
        public Nullable<decimal> eritrosedimentacion_1rahora { get; set; }
        public Nullable<decimal> eritrosedimentacion_2dahora { get; set; }
        public Nullable<decimal> neutrofilos_encayados_rel { get; set; }
        public Nullable<decimal> neutrofilos_encayados_abs { get; set; }
        public Nullable<decimal> neutrofilos_segmentados_rel { get; set; }
        public Nullable<decimal> neutrofilos_segmentados_abs { get; set; }
        public Nullable<decimal> eosinofilos_rel { get; set; }
        public Nullable<decimal> eosinofilos_abs { get; set; }
        public Nullable<decimal> basofilos_rel { get; set; }
        public Nullable<decimal> basofilos_abs { get; set; }
        public Nullable<decimal> linfositos_rel { get; set; }
        public Nullable<decimal> linfositos_abs { get; set; }
        public Nullable<decimal> monositos_rel { get; set; }
        public Nullable<decimal> monositos_abs { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
