//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Hepatograma
    {
        public tb_Analisis_Hepatograma()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_hepatograma { get; set; }
        public Nullable<decimal> got { get; set; }
        public Nullable<decimal> pgt { get; set; }
        public Nullable<decimal> fosfatasa_alcalina { get; set; }
        public Nullable<decimal> colesterol { get; set; }
        public Nullable<decimal> proteinas_totales { get; set; }
        public Nullable<decimal> albumina { get; set; }
        public Nullable<decimal> rel_albumina_globulina { get; set; }
        public Nullable<decimal> bilirrubina_directa { get; set; }
        public Nullable<decimal> bilirrubina_indirecta { get; set; }
        public Nullable<decimal> bilirrubina_total { get; set; }
        public Nullable<decimal> eritrosedimentacion_1rahora { get; set; }
        public Nullable<decimal> eritrosedimentacion_2dahora { get; set; }
        public Nullable<decimal> indice_de_katz { get; set; }
        public Nullable<decimal> uremia { get; set; }
        public Nullable<decimal> glucemia { get; set; }
        public Nullable<decimal> creatinina { get; set; }
        public Nullable<decimal> trigliceridos { get; set; }
        public Nullable<decimal> hdl_col { get; set; }
        public Nullable<decimal> ldl_col { get; set; }
        public Nullable<decimal> gamma_gt { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
