//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Alarmas_Stock
    {
        public tb_Alarmas_Stock()
        {
            this.tb_Alarma_x_Insumo = new HashSet<tb_Alarma_x_Insumo>();
        }
    
        // Primitive properties
    
        public int id_alarma { get; set; }
        public Nullable<int> estado { get; set; }
        public string detalle { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Alarma_x_Insumo> tb_Alarma_x_Insumo { get; set; }
    
    }
}
