//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Orina_Completa
    {
        public tb_Analisis_Orina_Completa()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
            this.tb_Analisis_Orina_Complementarios = new HashSet<tb_Analisis_Orina_Complementarios>();
            this.tb_Analisis_Orina_Examen_Fisico_Quimico = new HashSet<tb_Analisis_Orina_Examen_Fisico_Quimico>();
            this.tb_Analisis_Orina_Examen_Sedimento = new HashSet<tb_Analisis_Orina_Examen_Sedimento>();
        }
    
        // Primitive properties
    
        public int id_orina_completa { get; set; }
        public Nullable<int> analisis_id { get; set; }
        public Nullable<int> estado_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Complementarios> tb_Analisis_Orina_Complementarios { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Examen_Fisico_Quimico> tb_Analisis_Orina_Examen_Fisico_Quimico { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Examen_Sedimento> tb_Analisis_Orina_Examen_Sedimento { get; set; }
    
    }
}
