//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Inmunologia
    {
        // Primitive properties
    
        public int id_inmunologia { get; set; }
        public string reaccion_widall_antigeno_h { get; set; }
        public string reaccion_widall_antigeno_o { get; set; }
        public string reaccion_widall_paratifis_a { get; set; }
        public string reaccion_widall_paratifis_b { get; set; }
        public string reaccion_hudlesson_cualitativa { get; set; }
        public string reaccion_hudlesson_cuantitativa { get; set; }
        public string vdrl_cualitativa { get; set; }
        public string reaccion_wasserman_fta_abs { get; set; }
        public string chagas_hai_con_2me { get; set; }
        public string chagas_hai_sin_2me { get; set; }
        public string inmunoperoxidasa { get; set; }
        public string tif { get; set; }
        public string taxoplasmosis_hai_con_2me { get; set; }
        public string taxoplasmosis_hai_sin_2me { get; set; }
        public string anticuerpos_monoclonales { get; set; }
        public string inmunoperoxidasas { get; set; }
        public string tif_igm { get; set; }
        public string citomegalovirus_igg { get; set; }
        public string citomegalovirus_igm { get; set; }
        public string hiv_metodo_elisa { get; set; }
        public string rubeola_igg { get; set; }
        public string rubeola_igm { get; set; }
        public string brucelosis_wright { get; set; }
        public string brucelosis_hudlesson { get; set; }
        public string anti_hvc_hepatitis_metodo_elisa { get; set; }
        public string hbs_ag_metodo_elisa { get; set; }
        public string core_igm { get; set; }
        public string igm_anti_a { get; set; }
        public string eppstein_barr_igg { get; set; }
        public string eppstein_barr_igm { get; set; }
        public string monotest { get; set; }
        public string met_aglutinacion_especifica { get; set; }
        public string reaccion_waler_rose_ragan { get; set; }
        public Nullable<decimal> aslo { get; set; }
        public string artritest_igm { get; set; }
        public string artritest_pcr { get; set; }
        public string reaccion_weill_felix { get; set; }
        public string reaccion_compatibilidad_cruzada { get; set; }
        public string reaccion_complemento_c3 { get; set; }
        public string celulas_le { get; set; }
        public string reaccion_cooms_directa { get; set; }
        public string reaccion_cooms_indirecta { get; set; }
        public string anticuerpos_asma { get; set; }
        public string anticuerpos_ama { get; set; }
        public string anticuerpos_fan_ana { get; set; }
        public string anticuerpos_anca { get; set; }
        public string anticuerpos_dna { get; set; }
        public string anticuerpos_la { get; set; }
        public string anticuerpos_rnp { get; set; }
        public string anticuerpos_ro { get; set; }
        public string anticuerpos_ata { get; set; }
        public string inmunoglobulinas_igA { get; set; }
        public string inmunoglobulinas_igG { get; set; }
        public string inmunoglobulinas_igE { get; set; }
        public string inmunoglobulinas_igD { get; set; }
        public string helicobacter_pylori { get; set; }
        public string hidatidosis { get; set; }
        public string complemento_met_inmuno_difusion_radial_c3 { get; set; }
        public string complemento_met_inmuno_difusion_radial_c4 { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
