//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Alarma_x_Insumo
    {
        // Primitive properties
    
        public int id_alarmaxinsumo { get; set; }
        public Nullable<int> alarma_id { get; set; }
        public Nullable<int> insumo_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Insumos tb_Insumos { get; set; }
        public virtual tb_Alarmas_Stock tb_Alarmas_Stock { get; set; }
    
    }
}
