//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Orina_Examen_Sedimento
    {
        public tb_Analisis_Orina_Examen_Sedimento()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        // Primitive properties
    
        public int id_orina_examen_sed { get; set; }
        public string cel_descamacion_epitalial { get; set; }
        public string leucosios { get; set; }
        public string piocitos { get; set; }
        public string hematies { get; set; }
        public string cilindros { get; set; }
        public string filamentos_mucoides { get; set; }
        public string cristales { get; set; }
        public string hongos { get; set; }
        public string bacterias { get; set; }
        public string parasitos { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> examen_orina_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Analisis_Orina_Completa tb_Analisis_Orina_Completa { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    
    }
}
