//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis
    {
        public tb_Analisis()
        {
            this.tb_Factura_x_Analisis = new HashSet<tb_Factura_x_Analisis>();
            this.tb_Muestras = new HashSet<tb_Muestras>();
        }
    
        // Primitive properties
    
        public int id_analisis { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<int> medico_id { get; set; }
        public Nullable<int> enzim_id { get; set; }
        public Nullable<int> hepatog_id { get; set; }
        public Nullable<int> matfecal_id { get; set; }
        public Nullable<int> hemogram_id { get; set; }
        public Nullable<int> hemostaciaycoag_id { get; set; }
        public Nullable<int> hormonas_id { get; set; }
        public Nullable<int> inmunoglobul_id { get; set; }
        public Nullable<int> lipidogelectrof_id { get; set; }
        public Nullable<int> microbiolog_id { get; set; }
        public Nullable<int> orinacomplet_id { get; set; }
        public Nullable<int> orinacomplemen_id { get; set; }
        public Nullable<int> orinafisicoquimico_id { get; set; }
        public Nullable<int> orina_sediment_id { get; set; }
        public Nullable<int> proteinogelectroforetic_id { get; set; }
        public Nullable<int> quimica_hematica_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Analisis_Enzimologia tb_Analisis_Enzimologia { get; set; }
        public virtual tb_Analisis_Examen_MateriaFecal tb_Analisis_Examen_MateriaFecal { get; set; }
        public virtual tb_Analisis_Hemograma tb_Analisis_Hemograma { get; set; }
        public virtual tb_Analisis_Hemostacia_Coagulacion tb_Analisis_Hemostacia_Coagulacion { get; set; }
        public virtual tb_Analisis_Hepatograma tb_Analisis_Hepatograma { get; set; }
        public virtual tb_Analisis_Hormonas tb_Analisis_Hormonas { get; set; }
        public virtual tb_Analisis_Inmunoglobulinas tb_Analisis_Inmunoglobulinas { get; set; }
        public virtual tb_Analisis_LipidoGrama_Electroforetico tb_Analisis_LipidoGrama_Electroforetico { get; set; }
        public virtual tb_Analisis_Microbiologico tb_Analisis_Microbiologico { get; set; }
        public virtual tb_Analisis_Orina_Complementarios tb_Analisis_Orina_Complementarios { get; set; }
        public virtual tb_Analisis_Orina_Completa tb_Analisis_Orina_Completa { get; set; }
        public virtual tb_Analisis_Orina_Examen_Fisico_Quimico tb_Analisis_Orina_Examen_Fisico_Quimico { get; set; }
        public virtual tb_Analisis_Orina_Examen_Sedimento tb_Analisis_Orina_Examen_Sedimento { get; set; }
        public virtual tb_Analisis_Proteinograma_Electroforetico tb_Analisis_Proteinograma_Electroforetico { get; set; }
        public virtual tb_Analisis_Quimica_Hematica tb_Analisis_Quimica_Hematica { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
        public virtual tb_Pacientes tb_Pacientes { get; set; }
        public virtual ICollection<tb_Factura_x_Analisis> tb_Factura_x_Analisis { get; set; }
        public virtual ICollection<tb_Muestras> tb_Muestras { get; set; }
    
    }
}
