//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Barrio
    {
        // Primitive properties
    
        public int id_barrio { get; set; }
        public Nullable<int> localidad_id { get; set; }
        public string descripcion { get; set; }
    
        // Navigation properties
    
        public virtual Localidad Localidad { get; set; }
    
    }
}
