//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compras
    {
        // Primitive properties
    
        public int id_compra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string detalle { get; set; }
        public Nullable<int> notapedido_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_NotaPedido tb_NotaPedido { get; set; }
    
    }
}
