//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Diagnosticos
    {
        // Primitive properties
    
        public int id_diagnostico { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> borrado { get; set; }
    
        // Navigation properties
    
        public virtual tb_Pacientes tb_Pacientes { get; set; }
    
    }
}
