//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Direccion_x_Medico
    {
        // Primitive properties
    
        public int id_dir_x_medico { get; set; }
        public Nullable<int> medico_id { get; set; }
        public Nullable<int> direccion_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_DireccionTodos tb_DireccionTodos { get; set; }
        public virtual tb_Medicos tb_Medicos { get; set; }
    
    }
}
