//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Estado_Analisis
    {
        public tb_Estado_Analisis()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
            this.tb_Analisis_Enzimologia = new HashSet<tb_Analisis_Enzimologia>();
            this.tb_Analisis_Examen_MateriaFecal = new HashSet<tb_Analisis_Examen_MateriaFecal>();
            this.tb_Analisis_Hemograma = new HashSet<tb_Analisis_Hemograma>();
            this.tb_Analisis_Hemostacia_Coagulacion = new HashSet<tb_Analisis_Hemostacia_Coagulacion>();
            this.tb_Analisis_Hepatograma = new HashSet<tb_Analisis_Hepatograma>();
            this.tb_Analisis_Hormonas = new HashSet<tb_Analisis_Hormonas>();
            this.tb_Analisis_Inmunoglobulinas = new HashSet<tb_Analisis_Inmunoglobulinas>();
            this.tb_Analisis_Inmunologia = new HashSet<tb_Analisis_Inmunologia>();
            this.tb_Analisis_LipidoGrama_Electroforetico = new HashSet<tb_Analisis_LipidoGrama_Electroforetico>();
            this.tb_Analisis_Microbiologico = new HashSet<tb_Analisis_Microbiologico>();
            this.tb_Analisis_Orina_Complementarios = new HashSet<tb_Analisis_Orina_Complementarios>();
            this.tb_Analisis_Orina_Examen_Fisico_Quimico = new HashSet<tb_Analisis_Orina_Examen_Fisico_Quimico>();
            this.tb_Analisis_Orina_Examen_Sedimento = new HashSet<tb_Analisis_Orina_Examen_Sedimento>();
            this.tb_Analisis_Proteinograma_Electroforetico = new HashSet<tb_Analisis_Proteinograma_Electroforetico>();
            this.tb_Analisis_Quimica_Hematica = new HashSet<tb_Analisis_Quimica_Hematica>();
        }
    
        // Primitive properties
    
        public int id_estado { get; set; }
        public string detalles { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual ICollection<tb_Analisis_Enzimologia> tb_Analisis_Enzimologia { get; set; }
        public virtual ICollection<tb_Analisis_Examen_MateriaFecal> tb_Analisis_Examen_MateriaFecal { get; set; }
        public virtual ICollection<tb_Analisis_Hemograma> tb_Analisis_Hemograma { get; set; }
        public virtual ICollection<tb_Analisis_Hemostacia_Coagulacion> tb_Analisis_Hemostacia_Coagulacion { get; set; }
        public virtual ICollection<tb_Analisis_Hepatograma> tb_Analisis_Hepatograma { get; set; }
        public virtual ICollection<tb_Analisis_Hormonas> tb_Analisis_Hormonas { get; set; }
        public virtual ICollection<tb_Analisis_Inmunoglobulinas> tb_Analisis_Inmunoglobulinas { get; set; }
        public virtual ICollection<tb_Analisis_Inmunologia> tb_Analisis_Inmunologia { get; set; }
        public virtual ICollection<tb_Analisis_LipidoGrama_Electroforetico> tb_Analisis_LipidoGrama_Electroforetico { get; set; }
        public virtual ICollection<tb_Analisis_Microbiologico> tb_Analisis_Microbiologico { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Complementarios> tb_Analisis_Orina_Complementarios { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Examen_Fisico_Quimico> tb_Analisis_Orina_Examen_Fisico_Quimico { get; set; }
        public virtual ICollection<tb_Analisis_Orina_Examen_Sedimento> tb_Analisis_Orina_Examen_Sedimento { get; set; }
        public virtual ICollection<tb_Analisis_Proteinograma_Electroforetico> tb_Analisis_Proteinograma_Electroforetico { get; set; }
        public virtual ICollection<tb_Analisis_Quimica_Hematica> tb_Analisis_Quimica_Hematica { get; set; }
    
    }
}
