//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Email_x_donante
    {
        // Primitive properties
    
        public int id_email_x_donante { get; set; }
        public Nullable<int> email_id { get; set; }
        public Nullable<int> donante_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Donantes tb_Donantes { get; set; }
        public virtual tb_EmailsTodos tb_EmailsTodos { get; set; }
    
    }
}
