//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailsTodos
    {
        public tb_EmailsTodos()
        {
            this.tb_Email_x_donante = new HashSet<tb_Email_x_donante>();
            this.tb_Email_x_Paciente = new HashSet<tb_Email_x_Paciente>();
        }
    
        // Primitive properties
    
        public int id_email { get; set; }
        public string email { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Email_x_donante> tb_Email_x_donante { get; set; }
        public virtual ICollection<tb_Email_x_Paciente> tb_Email_x_Paciente { get; set; }
    
    }
}
