//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Factura_x_Analisis
    {
        // Primitive properties
    
        public int id_factura_x_paciente { get; set; }
        public Nullable<int> factura_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Analisis tb_Analisis { get; set; }
        public virtual tb_Factura tb_Factura { get; set; }
    
    }
}
