//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Insumos
    {
        public tb_Insumos()
        {
            this.tb_Alarma_x_Insumo = new HashSet<tb_Alarma_x_Insumo>();
            this.tb_Insumos_x_Informe_Stock = new HashSet<tb_Insumos_x_Informe_Stock>();
        }
    
        // Primitive properties
    
        public int id_insumo { get; set; }
        public string detalle { get; set; }
        public Nullable<int> laboratorio_marca { get; set; }
        public string nombre_prod { get; set; }
        public Nullable<int> cant_minima { get; set; }
        public Nullable<int> medida { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
        public Nullable<int> cant_disponible { get; set; }
        public Nullable<int> tipo_id { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Alarma_x_Insumo> tb_Alarma_x_Insumo { get; set; }
        public virtual tb_Medida_Insumo tb_Medida_Insumo { get; set; }
        public virtual tb_Tipo_Insumo tb_Tipo_Insumo { get; set; }
        public virtual ICollection<tb_Insumos_x_Informe_Stock> tb_Insumos_x_Informe_Stock { get; set; }
    
    }
}
