//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IVA
    {
        public tb_IVA()
        {
            this.tb_Factura = new HashSet<tb_Factura>();
        }
    
        // Primitive properties
    
        public int id_iva { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Factura> tb_Factura { get; set; }
    
    }
}
