//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Muestras
    {
        // Primitive properties
    
        public int id_muestra { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<System.DateTime> fecha_extraccion { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public Nullable<int> analisis_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Analisis tb_Analisis { get; set; }
        public virtual tb_Muestras_Tipo tb_Muestras_Tipo { get; set; }
        public virtual tb_Pacientes tb_Pacientes { get; set; }
    
    }
}
