//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Muestras_Tipo
    {
        // Primitive properties
    
        public int id_muestras_tipo { get; set; }
        public string descripcion { get; set; }
    
        // Navigation properties
    
        public virtual tb_Muestras tb_Muestras { get; set; }
    
    }
}
