//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NotaPedido
    {
        public tb_NotaPedido()
        {
            this.tb_Compras = new HashSet<tb_Compras>();
        }
    
        // Primitive properties
    
        public int id_nota_pedido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> informeStock_id { get; set; }
        public Nullable<int> estado { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Compras> tb_Compras { get; set; }
        public virtual tb_InformeStock tb_InformeStock { get; set; }
    
    }
}
