//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ObraSocial
    {
        public tb_ObraSocial()
        {
            this.tb_Contacto_ObraSocial = new HashSet<tb_Contacto_ObraSocial>();
            this.tb_Direccion_x_ObraSocial = new HashSet<tb_Direccion_x_ObraSocial>();
            this.tb_Telefonos_x_ObraSocial = new HashSet<tb_Telefonos_x_ObraSocial>();
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        // Primitive properties
    
        public int id_obra_social { get; set; }
        public string razon_social { get; set; }
        public string website1 { get; set; }
        public string website2 { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Contacto_ObraSocial> tb_Contacto_ObraSocial { get; set; }
        public virtual ICollection<tb_Direccion_x_ObraSocial> tb_Direccion_x_ObraSocial { get; set; }
        public virtual ICollection<tb_Telefonos_x_ObraSocial> tb_Telefonos_x_ObraSocial { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    
    }
}
