//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Pacientes
    {
        public tb_Pacientes()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
            this.tb_Diagnosticos = new HashSet<tb_Diagnosticos>();
            this.tb_Donantes = new HashSet<tb_Donantes>();
            this.tb_Email_x_Paciente = new HashSet<tb_Email_x_Paciente>();
            this.tb_Factura = new HashSet<tb_Factura>();
            this.tb_Muestras = new HashSet<tb_Muestras>();
            this.tb_DireccionTodos = new HashSet<tb_DireccionTodos>();
            this.tb_TelefonosTodos = new HashSet<tb_TelefonosTodos>();
        }
    
        // Primitive properties
    
        public int id_paciente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> dni { get; set; }
        public Nullable<int> grupo_sanguineo { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> obra_social_id { get; set; }
        public Nullable<int> medico_id { get; set; }
        public Nullable<int> es_donante { get; set; }
        public Nullable<int> donante_id { get; set; }
        public Nullable<int> borrado { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual ICollection<tb_Diagnosticos> tb_Diagnosticos { get; set; }
        public virtual ICollection<tb_Donantes> tb_Donantes { get; set; }
        public virtual tb_Donantes tb_Donantes1 { get; set; }
        public virtual ICollection<tb_Email_x_Paciente> tb_Email_x_Paciente { get; set; }
        public virtual ICollection<tb_Factura> tb_Factura { get; set; }
        public virtual tb_GrupoSanguineo tb_GrupoSanguineo { get; set; }
        public virtual tb_Medicos tb_Medicos { get; set; }
        public virtual ICollection<tb_Muestras> tb_Muestras { get; set; }
        public virtual tb_ObraSocial tb_ObraSocial { get; set; }
        public virtual ICollection<tb_DireccionTodos> tb_DireccionTodos { get; set; }
        public virtual ICollection<tb_TelefonosTodos> tb_TelefonosTodos { get; set; }
    
    }
}
