//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Telefonos_x_ObraSocial
    {
        // Primitive properties
    
        public int id_telefono_x_os { get; set; }
        public Nullable<int> telefono_id { get; set; }
        public Nullable<int> obra_social_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_ObraSocial tb_ObraSocial { get; set; }
        public virtual tb_TelefonosTodos tb_TelefonosTodos { get; set; }
    
    }
}
