//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Tipo_Insumo
    {
        public tb_Tipo_Insumo()
        {
            this.tb_Insumos = new HashSet<tb_Insumos>();
        }
    
        // Primitive properties
    
        public int id_tipo_insumo { get; set; }
        public string detalles { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Insumos> tb_Insumos { get; set; }
    
    }
}
