//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public tb_Usuarios()
        {
            this.tb_InformeStock = new HashSet<tb_InformeStock>();
        }
    
        // Primitive properties
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string cargo { get; set; }
        public Nullable<int> permisos { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> ultimo_acceso { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public string email2 { get; set; }
        public string direccion { get; set; }
        public string direccion2 { get; set; }
        public string password { get; set; }
        public string username { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_InformeStock> tb_InformeStock { get; set; }
    
    }
}
